### ISSUE TITLE
sort books by publication_date

### ISSUE THREAD

**Issue by ryandeussing** [theNewDynamic/dallashudgens.com#1]
`{{ range (sort .Site.Sections.book.Pages "publication_date" "desc") }}` doesn't do it

**Comment by budparr** [comment]
Hey, @ryandeussing So this is sort of a Hugo issue. I think that Hugo just treats `publication_date` like a string so can't really sort by it. We need to change to it `date.` Fortunately, Hugo natively solves the problem that I had used publication_date for anyway. Jekyll uses date to determine if something should show up or not (so it won't unless you have "future: true" set in the config, which can cause problems because some things you may want to show future and others not, hence the field. Hugo has two native fields, date, and published_date so that you can manipulate how things show up a bit more easily.
